src/main/java/org/folio/processor/ReferenceData.java
src/main/java/org/folio/processor/RuleProcessor.java
src/main/java/org/folio/processor/translations/ReferenceDataConstants.java
src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/TestUtil.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/resources/mockData/inventory/get_contributor_name_types_response.json
src/test/resources/mockData/inventory/get_electronic_access_relationships_response.json
src/test/resources/mockData/inventory/get_identifier_types_response.json
src/test/resources/mockData/inventory/get_instance_formats_response.json
src/test/resources/mockData/inventory/get_instance_types_response.json
src/test/resources/mockData/inventory/get_locations_response.json
src/test/resources/mockData/inventory/get_material_types_response.json
src/test/resources/mockData/inventory/get_nature_of_content_terms_response.json

Moved implementation of TranslationFunction to the library.

MDEXP-255 Add translationFunction to the library

---

src/main/java/org/folio/processor/rule/Rule.java

Add a new id field to Rule to have possibility selecting default rule by id

MDEXP-141 Add id field to the Rule

---

src/main/java/org/folio/processor/translations/ReferenceDataConstants.java
src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/resources/mockData/inventory/get_campuses_response.json
src/test/resources/mockData/inventory/get_institutions_response.json
src/test/resources/mockData/inventory/get_libraries_response.json
src/test/resources/mockData/inventory/get_locations_response.json

Add a new translation function to set location and related reference data (library, campus, institution)

MDEXP-252 Applying mapping profile - location fields - holdings and item

---

src/main/java/org/folio/processor/translations/ReferenceDataConstants.java
src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/resources/mockData/inventory/get_loan_types_response.json
src/test/resources/mockData/inventory/get_mode_of_issuance_response.json

https://issues.folio.org/browse/MDEXP-279
To map the permanent loan type , we need a translation function. This PR contains the translation function
Needs to be merged along with https://github.com/folio-org/mod-data-export/pull/152

MDEXP-279: adding loan type function

---

src/main/java/org/folio/processor/translations/ReferenceDataConstants.java
src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/java/org/folio/processor/RuleProcessorTest.java
src/test/java/org/folio/util/ReferenceDataResponseUtil.java
src/test/java/org/folio/util/TestUtil.java
src/test/resources/mockData/inventory/get_call_number_types_response.json

https://issues.folio.org/browse/MDEXP-249
**PURPOSE:**
The PR contains a translation function for the effective call number type.
**NOTES:**
Need to be merged before PR for MDEXP-249 in mod-data-export module will be merged.

MDEXP-249 Add function for effective call number

---

src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java

**Purpose:**
https://issues.folio.org/browse/MDEXP-282
**Approach:**
Added function for metadata created/updated time

MDEXP-282 Add metadata-date-time function

---

src/main/java/org/folio/processor/translations/ReferenceDataConstants.java

**PURPOSE:**
https://issues.folio.org/browse/MDEXP-301
**APPROACH:**
Changed the key value for the material type field in reference data.

MDEXP-301 Fix NPE while export with material types

---

src/main/java/org/folio/processor/rule/DataSource.java
src/main/java/org/folio/processor/rule/Rule.java
src/main/java/org/folio/reader/JPathSyntaxEntityReader.java
src/test/java/org/folio/processor/RuleProcessorTest.java

Main PR https://github.com/folio-org/mod-data-export/pull/176

MDEXP-266 Generate MARC record- Holdings and items in same field

---

.gitignore
Jenkinsfile
NEWS.md
pom.xml

https://issues.folio.org/browse/MDEXP-290
- Updated to latest RMB version
- Added NEWS.md- did not include individual stories as we usually do because many stories have major portion of them in mod-data-export project, it might be difficult to track all the stories with related PRs going forward. 
- Upgrade to Java 11

MDEXP-290- Release 1.0.0

---

pom.xml

https://issues.folio.org/browse/MDEXP-307
- Update guava to the latest release

MDEXP-307: Guava security fix

---

src/main/java/org/folio/processor/error/ErrorCode.java

https://issues.folio.org/browse/MDEXP-318
Update error codes according to the general convention to use it for localization

MDEXP-318 Update error codes

---

src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java

**Purpose:**
https://issues.folio.org/browse/MDEXP-12
**Approach:**
1. Create a new translation function, if temporaryLocationId is present - empty string return, otherwise - the name of a permanent location.

MDEXP-12 Create translation function for holding permanent location

---

PERSONAL_DATA_DISCLOSURE.md

**PURPOSE**
https://issues.folio.org/browse/MDEXP-358
**APPROACH:**
Add personal disclosure form to gmu

MDEXP-358 Add disclosure form

---

src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/resources/mockData/inventory/get_identifier_types_response.json

https://issues.folio.org/browse/MDEXP-191
Add new translation function SET_RELATED_IDENTIFIER. Should return value corresponds to the type identifier param from translation in the case when the current identifier type that applied to function matches related identifier type params from translation.

MDEXP-191 Add new translation function related identifiers

---

pom.xml
src/main/java/org/folio/processor/RuleProcessor.java
src/main/java/org/folio/processor/error/Error.java
src/main/java/org/folio/processor/error/ErrorCode.java
src/main/java/org/folio/processor/referencedata/JsonObjectWrapper.java
src/main/java/org/folio/processor/referencedata/ReferenceDataWrapper.java
src/main/java/org/folio/processor/referencedata/ReferenceDataWrapperImpl.java
src/main/java/org/folio/processor/translations/TranslationFunction.java
src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/main/java/org/folio/reader/JPathSyntaxEntityReader.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/java/org/folio/processor/RuleProcessorTest.java
src/test/java/org/folio/util/ReferenceDataResponseUtil.java

Jira: https://issues.folio.org/browse/GMU-2
**PURPOSE**
since the library doesn't use the RMB, related dependency should be removed. Also should be removed vertx dependency and created wrapper which will be used instead of `JsonObject`.

GMU-2 Remove RMB and vertx dependencies

---

src/main/java/org/folio/processor/RuleProcessor.java
src/main/java/org/folio/processor/error/RecordInfo.java
src/test/java/org/folio/processor/RuleProcessorTest.java
src/test/resources/processor/given_entity_one_holding_one_item.json

**Purpose:**
https://issues.folio.org/browse/MDEXP-367
**Approach:**
Changed RecordInfo object,  added fieldName, fieldValue fields, to let the user know in error log what fields are failed to map.

MDEXP-367 Add fields data to record info

---

NEWS.md
pom.xml

https://issues.folio.org/browse/GMU-4
This major release includes improving error handling to detect which record exactly leads to the exception, adding new translation functions for Related Identifiers and Holdings Permanent Location fields, removing RMB and Vert.x dependencies, and adding personal data disclosure form.

GMU-4 - Release 1.1.0 

---

pom.xml

[GMU-10](https://issues.folio.org/browse/GMU-10) - Kiwi R3 2021 - Log4j vulnerability verification and correction

GMU-10 - Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

[GMU-13](https://issues.folio.org/browse/GMU-13) - GMU (generate-marc-utils) Kiwi Bugfix release

GMU-13 - Release 1.3.1

---

NEWS.md
pom.xml

[GMU-15](https://issues.folio.org/browse/GMU-15) - GMU (generate-marc-utils) Iris Hotfix release

GMU-15 - Release 1.1.2

---

src/main/java/org/folio/processor/referencedata/ReferenceDataConstants.java
src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java
src/test/java/org/folio/util/ReferenceDataResponseUtil.java
src/test/resources/mockData/inventory/get_alternative_title_types_response.json

[GMU-25](https://issues.folio.org/browse/GMU-25) - Add alternative titles type usage
Add special operation to set value for the marc record from alternative titles type
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

GMU-25 - Add alternative titles type usage

---

NEWS.md
pom.xml

[GMU-22](https://issues.folio.org/browse/GMU-22) - GMU (generate-marc-utils) release

GMU-22 - Release 1.4.0

---

src/main/java/org/folio/reader/JPathSyntaxEntityReader.java
src/test/java/org/folio/processor/RuleProcessorTest.java
src/test/resources/processor/given_multiple_holdings_with_multiple_holdings_notes.json
src/test/resources/processor/mapped_json_holdings_notes_record.json

[GMU-34](https://issues.folio.org/browse/GMU-34) - Holdings notes not being exported properly in MARC Bibs when there are multiple holdings
Fix mapping for holdings notes.
When building composite value from matrix, remove holdings notes which not belong to the holding being processed.
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in …

GMU-34 - Holdings notes not being exported properly in MARC Bibs when there are multiple holdings

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties

[GMU-35](https://issues.folio.org/browse/GMU-35) - Logging improvement - Configuration

GMU-35 - Logging improvement - Configuration

---

NEWS.md
pom.xml

[GMU-37](https://issues.folio.org/browse/GMU-37) - generate-marc-utils: module release

Release 1.6.0

---

src/main/java/org/folio/processor/translations/TranslationsFunctionHolder.java
src/test/java/org/folio/holder/TranslationFunctionHolderUnitTest.java

Revert "GMU-39 - Electronic access indicator setter function should return empty value by default (#71)

Revert "GMU-39 - Electronic access indicator setter function should return empty value by default (#71)

---

NEWS.md
pom.xml

[GMU-40](https://issues.folio.org/browse/GMU-40) - generate-marc-utils: module release
Release 1.7.0 version.

GMU-40 - generate-marc-utils: module release

---

NEWS.md
pom.xml

[FOLIO-4101](https://folio-org.atlassian.net/browse/FOLIO-4101) - Release 1.9.0

FOLIO-4101 - Release 1.9.0

---

Jenkinsfile
pom.xml
src/main/java/org/folio/processor/error/Error.java

[GMU-51](https://folio-org.atlassian.net/browse/GMU-51) - Update to generate-marc-utils Java 21
Java version upgrading

GMU-51 - Update to generate-marc-utils Java 21

---

pom.xml

GMU-51 revert log4j upgrade

---

NEWS.md
pom.xml

[GMU-52](https://folio-org.atlassian.net/browse/GMU-52) - Release 1.10.0

GMU-52 - Release 1.10.0
